'use strict'
module.exports = [
    {
        "email": "lrhymer0@shutterfly.com",
        "username": "cpickersail0",
        "description": "Wedg resec entropion rep",
        "img": "placeholder",
        "listing_name": "Heller's Cudweed",
        "expiry_date": "07/22/2020",
        "location": "Serangoon",
        "category": "Canned Food",
        "created_at": "07/07/2017",
        "updated_at": "07/07/2017",
    },
    {
        "email": "stabrett1@vistaprint.com",
        "username": "fsives1",
        "description": "Insert bone stim-humerus",
        "img": "placeholder",
        "listing_name": "Tropical Sensitive Pea",
        "expiry_date": "08/02/2020",
        "location": "Woodlands",
        "category": "Biscuits",
        "created_at": "07/07/2017",
        "updated_at": "07/07/2017",
    },
    {
        "email": "hroskeilly2@dot.gov",
        "username": "apinsent2",
        "description": "Proctoclysis",
        "img": "placeholder",
        "listing_name": "Bolivian Walnut",
        "expiry_date": "06/21/2020",
        "location": "Central",
        "category": "Drinks",
        "created_at": "07/07/2017",
        "updated_at": "07/07/2017",
    },
    {
        "email": "scolmer3@wikia.com",
        "username": "mcancellor3",
        "description": "Egd with closed biopsy",
        "img": "placeholder",
        "listing_name": "Douglas' Buckwheat",
        "expiry_date": "12/04/2019",
        "location": "Bishan",
        "category": "Fruits",
        "created_at": "07/07/2017",
        "updated_at": "07/07/2017",
    }
]
